

development:
        coms:
                papers_path: /home/www/virtual/physcon.ru/ph1/entry/coms/papers/
        pg:
                conn:
                        dbname: db00060892
                        host: localhost
                        user: db00060892
                        password: rjulfytjn[elfbytjnlj,hf
                schema: userschema, cmsmlschema, comsml01, coms01, membership01
        mongo:
                host: localhost
                #dbname: ph3_dev
                dbname: ph3

test:

production:
        coms:
                papers_path: /home/www/virtual/physcon.ru/ph1/entry/coms/papers/
        pg:
                conn:
                        dbname: db00060892
                        host: localhost
                        user: db00060892
                        password: rjulfytjn[elfbytjnlj,hf
                schema: userschema, cmsmlschema, comsml01, coms01, membership01
        mongo:
                host: localhost
                dbname: ph3


